[Us-11] get voting history
ces-hoangdao/BE-SummerIntern-2023 pull request #38
Opened 2023-07-06 06:46 UTC by TMNhat1810

-add voting history API and its docs
-add socket handling vote
-mini change in history model

2023-07-06 09:57 UTC, LongTCH approved these changes

2023-07-06 10:39 UTC, ces-anduynguyen requested changes

2023-07-06 10:39 UTC, ces-anduynguyen commented on app/utils/history.js
> +  getVoteSummary: (votes) => {
don't need to put this function into `historyHelper`, `export const getVoteSummary = (votes) => {}` is enough

2023-07-06 10:39 UTC, ces-anduynguyen commented on app/utils/history.js
> +    let [voteCount, numberCount, voteSum] = [0, 0, 0];
`numberCount` should be `userCount` I think? :thinking:

2023-07-06 10:39 UTC, ces-anduynguyen commented on app/utils/history.js
> +        else if (userVoting.vote !== '?') {
should define an enum for `coffee` & `?`
ex: 
```
enum ExtraVote {
  Coffee = 'coffee',
  QuestionMark = '?',
}
```

2023-07-06 10:39 UTC, ces-anduynguyen commented on app/utils/history.js
> +      results = coffeeTime ? 'coffee' : '?';
remember to use enum above once we define it

2023-07-06 10:39 UTC, ces-anduynguyen commented on app/services/room.js
> +    return null;
can do an early return here: 
```
if (!room) {
 return null;
}
const { results, voteOnTotal, playerResults, coffeeTime } = historyHelper.getVoteSummary(room.voting);
...
return history;
```

2023-07-06 10:39 UTC, ces-anduynguyen commented on app/services/room.js
> +      return true;
do we need this return? :thinking:

2023-07-06 10:39 UTC, ces-anduynguyen commented on app/utils/history.js
> +    let [results, voteOnTotal, playerResults] = ['', '', ''];
how about making these variables become an object from the beginning instead of defining a variable using `let`? :thinking: 
ex: `const obj = { results: '', voteCount: 0, coffeeTime: false, ... }`

2023-07-06 12:35 UTC, TMNhat1810 commented on app/services/room.js
> +      return true;
actually.. not

2023-07-06 12:36 UTC, TMNhat1810 commented on app/utils/history.js
> +    let [results, voteOnTotal, playerResults] = ['', '', ''];
i've tried it, but it become hard to get through because I need to access them many time

2023-07-06 23:47 UTC, ces-anduynguyen approved these changes

2023-07-06 23:47 UTC, ces-anduynguyen commented on app/utils/history.js
> +  });
```
votes.forEach((userVoting) => {
    const { username, vote } = userVoting; // Destructuring assignment

    if (vote) {
      voteCount++;
      playerResults += `${username} (${vote}), `;

      if (vote === EXTRA_VOTE.COFFEE) {
        coffeeTime = true;
      } else if (vote !== EXTRA_VOTE.QUESTION_MARK) {
        numericVoteCount++;
        voteSum += parseInt(vote);
      }
    }
  });
```

2023-07-06 23:52 UTC, ces-anduynguyen commented on app/utils/history.js
> +    let [results, voteOnTotal, playerResults] = ['', '', ''];
```
export const getVoteSummary = (votes) => {
  const summary = {
    playerResults: [], // convert to string using join(', ') method
    voteCount: 0,
    numericVoteCount: 0,
    voteSum: 0,
    coffeeTime: false,
  };

  votes.forEach((userVoting) => {
    const { username, vote } = userVoting;

    if (vote) {
      summary.voteCount++;
      summary.playerResults.push(`${username} (${vote})`);

      if (vote === EXTRA_VOTE.COFFEE) {
        summary.coffeeTime = true;
      } else if (vote !== EXTRA_VOTE.QUESTION_MARK) {
        summary.numericVoteCount++;
        summary.voteSum += parseInt(vote);
      }
    }
  });

  summary.voteOnTotal = `${summary.voteCount}/${votes.length}`;

  if (summary.numericVoteCount === 0) {
    summary.results = summary.coffeeTime ? EXTRA_VOTE.COFFEE : EXTRA_VOTE.QUESTION_MARK;
  } else {
    summary.results = (summary.voteSum / summary.numericVoteCount).toString();
  }

  return summary;
};
```
By using an object to encapsulate related variables, you maintain a clear structure and improve code readability. This helps organize the variables under a single entity, making the code more cohesive.

2023-07-07 03:44 UTC, ces-hoangdao approved these changes

2023-07-07 03:45 UTC, merged