feat: add change room name, issue name; modified data flow via socket
ces-hoangdao/BE-SummerIntern-2023 pull request #39
Opened 2023-07-10 03:53 UTC by TMNhat1810

-add feature change room name, issue name
-add fullConsensus check on reveal

2023-07-10 10:10 UTC, ces-anduynguyen commented on app/utils/history.js
> +    }
Why do we need this? Are we looping `votes` again inside `votes.forEach()`?

2023-07-10 10:35 UTC, ces-anduynguyen requested changes

2023-07-10 10:35 UTC, ces-anduynguyen commented on app/utils/history.js
> +    }
should extract this into another function that returns `fullConsensus` status
`fullConsensus = getFullConsensus(votes)`

2023-07-10 10:35 UTC, ces-anduynguyen commented on app/utils/history.js
>      if (userVoting.vote) {
```
votes.forEach((userVoting) => {
    const { vote, username } = userVoting;
    if (vote) {
      voteCount += 1;
      playerResults += `${username} (${vote}), `;
      if (vote === EXTRA_VOTE.COFFEE) coffeeTime = true;
      else if (vote !== EXTRA_VOTE.QUESTION_MARK) {
        numbericVoteCount += 1;
        voteSum += parseInt(userVoting.vote);
      }
    }
```

2023-07-10 10:48 UTC, TMNhat1810 commented on app/utils/history.js
>      if (userVoting.vote) {
got it

2023-07-10 10:48 UTC, TMNhat1810 commented on app/utils/history.js
> +    }
got it

2023-07-11 07:48 UTC, ces-anduynguyen approved these changes

2023-07-11 09:06 UTC, merged