feat: init database
ces-hoangdao/BE-SummerIntern-2023 pull request #6
Opened 2023-06-20 03:05 UTC by LongTCH

add history, issue, room, user

2023-06-20 03:14 UTC, TMNhat1810 approved these changes

2023-06-20 04:40 UTC, ces-hoangdao approved these changes

2023-06-20 08:01 UTC, ces-hoangdao commented on app/models/issue.js
> +	storyPoint: {
storyPoints

2023-06-20 11:16 UTC, ces-anduynguyen requested changes

2023-06-20 11:16 UTC, ces-anduynguyen commented on app/models/room.js
> +	ROOM_NAME_DEFAULT,
should use file format, a little bit messy here, can try `Prettier`
Read more here: [Format Code with Prettier](https://www.digitalocean.com/community/tutorials/how-to-format-code-with-prettier-in-visual-studio-code)

2023-06-20 11:16 UTC, ces-anduynguyen commented on app/models/room.js
> +const votingSchema = new Schema(
Why is `votingSchema` in `room.js`? Should move this to another file `model/voting.js`

2023-06-20 11:16 UTC, ces-anduynguyen commented on app/models/room.js
> +		enum: [ROOM_STATUSES.READY, ROOM_STATUSES.VOTING, ROOM_STATUSES.CONCLUDED],
Is ROOM_STATUSES enum?
1. Enum should be CamelCase: `RoomStatuses`
2. If you want to get all values of RoomStatuses, just use `Object.values(RoomStatuses)`

2023-06-20 11:16 UTC, ces-anduynguyen commented on app/models/history.js
> +	room: mongoose.Types.ObjectId,
not sure but we should use mongoose.Schema.Types instead of mongoose.Types
[What is the difference between mongoose.Schema.Types and mongoose.Types?](https://github.com/Automattic/mongoose/issues/1671#issuecomment-23437880)

2023-06-20 11:16 UTC, ces-anduynguyen commented on app/models/user.js
> +		enum: [USER_TYPES.GUEST, USER_TYPES.EMAIL, USER_TYPES.GOOGLE],
same above for enum type

2023-06-21 04:15 UTC, LongTCH commented on app/models/issue.js
> +	room: mongoose.Types.ObjectId,
resolved

2023-06-21 04:15 UTC, LongTCH commented on app/models/history.js
> +	room: mongoose.Types.ObjectId,
resolved

2023-06-21 04:15 UTC, LongTCH commented on app/models/room.js
> +	ROOM_NAME_DEFAULT,
resolved

2023-06-21 04:15 UTC, LongTCH commented on app/models/room.js
> +		enum: [ROOM_STATUSES.READY, ROOM_STATUSES.VOTING, ROOM_STATUSES.CONCLUDED],
resolved

2023-06-21 04:15 UTC, LongTCH commented on app/models/user.js
> +		enum: [USER_TYPES.GUEST, USER_TYPES.EMAIL, USER_TYPES.GOOGLE],
resolved

2023-06-21 04:16 UTC, LongTCH commented on app/models/room.js
> +const votingSchema = new Schema(
resolved

2023-06-21 07:04 UTC, ces-hoangdao approved these changes

2023-06-21 10:34 UTC, merged